@host = http://localhost:3000
@tokenAdmin=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTMsIm5vbWJyZSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJyb2wiOiJhZG1pbiIsImlhdCI6MTczMTg3MDk3OX0.rZhmXH_lNeJp8g9g41dVAtG_C3zLz42-QWYczLL8xcE
@tokenEditor = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAsIm5vbWJyZSI6IkphaW1lIiwiZW1haWwiOiJqYWltZUBnbWFpbC5jb20iLCJyb2wiOiJlZGl0b3IiLCJpYXQiOjE3MzE4NzA4MzZ9.ODDSaTvbZQCYkdJSCUliwir_KDjXAyro2yt08E67sHY
@tokenRedactor = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTIsIm5vbWJyZSI6InJlZGFjdG9yIiwiZW1haWwiOiJyZWRhY3RvckBnbWFpbC5jb20iLCJyb2wiOiJyZWRhY3RvciIsImlhdCI6MTczMTg3MDk5NH0.LpYHlIF4AGcdwy7l8TpzkVhlCF-l5gv1exXsI1bmMKU

### ----------------------Peticiones CATEGORIAS------------
### GET todas las categorias
GET {{host}}/api/categorias

### GET una categoria por id
GET {{host}}/api/categorias/5

### ----------------------Peticiones NOTICIAS------------
###
GET {{host}}/api/noticias/5

###
GET {{host}}/api/noticias/usuarios/2

###
GET {{host}}/api/noticias/?seccion=secundario&categoria=deportes

###
POST {{host}}/api/noticias
Content-Type: application/json
Authorization: {{tokenRedactor}}

{
  "titular": "Los españoles vuelven a la montaña",
  "imagen": "https://img.freepik.com/fotos-premium/montanas-georgia-rios-montana_73944-8400.jpg",
  "texto": "El nuevo destino turístico para los españoles es la montaña, superando por primera vez a la playa",
  "secciones": "destacado",
  "fecha_publicacion": "2024-10-29",
  "redactor_id": 1,
  "editor_id": 4,
  "categoria_id": 5,
  "estado": "borrador",
  "importancia": 10,
  "cambios": null,
  "slug": "turismo-montana-economia-nueva1"
}

###
PUT {{host}}/api/noticias/18
Content-Type: application/json
Authorization: {{tokenRedactor}}

{
  "titular": "Los españoles nunca van a la montaña",
  "imagen": "https://img.freepik.com/fotos-premium/montanas-georgia-rios-montana_73944-8400.jpg",
  "texto": "El viejo destino turístico para los españoles es la montaña, superando por primera vez a la playa",
  "secciones": "destacado",
  "fecha_publicacion": "2024-10-29",
  "redactor_id": 1,
  "editor_id": 4,
  "categoria_id": 5,
  "estado": "borrador",
  "importancia": 10,
  "cambios": null,
  "slug": "turismo-montana"
}

###
DELETE {{host}}/api/noticias/18
Authorization: {{tokenRedactor}}

### ----------------------Peticiones USUARIOS------------  

### Obtener todos los usuarios
GET {{host}}/api/usuarios
Authorization: {{tokenRedactor}}

### Obtener un usuario por id
GET {{host}}/api/usuarios/5
Authorization: {{tokenRedactor}}

### Login de usuario
POST {{host}}/api/usuarios/login
Content-Type: application/json

{
  "email": "redactor@gmail.com",
  "contraseña": "1234"
}

### Registrar un usuario
POST {{host}}/api/usuarios
Content-Type: application/json
Authorization: {{tokenRedactor}}

{
  "nombre": "admin",
  "email": "admin@gmail.com",
  "contraseña": "1234",
  "rol": "admin"
}

### Actualizar un usuario  // Puede ser redactor o editor
PUT {{host}}/api/usuarios/6
Content-Type: application/json
Authorization: {{tokenRedactor}}

{
  "nombre": "admin1",
  "email": "admin@gmail.com",
  "contraseña": "1234",
  "rol": "admin"
}

### Eliminar un usuario
DELETE {{host}}/api/usuarios/7
Authorization: {{tokenRedactor}}

### ----------------------Peticiones SUSCRIPTORES------------  

### Obtener todos los suscriptores
GET {{host}}/api/suscriptores

### Obtener un suscriptor por id
GET {{host}}/api/suscriptores/4

### Obtener un suscriptor por email --> OJO /email/ 
GET {{host}}/api/suscriptores/email/jaime@gmail.com

### Registrar un NUEVO suscriptor
POST {{host}}/api/suscriptores
Content-Type: application/json

{
  "email": "jaimepavonp@gmail.com",
  "categorias":[1,2,3]
}

### Activar suscriptor 
GET {{host}}/api/suscriptores/activar/33/1

### Actualizar un suscriptor 
PUT {{host}}/api/suscriptores/30
Content-Type: application/json

{
  "email": "jaimePavonp@gmail.com"
}

### Eliminar un suscriptor POR ID  ---> OJO NO USAR ESTA
DELETE {{host}}/api/suscriptores/31

### Eliminar un suscriptor POR EMAIL
DELETE {{host}}/api/suscriptores/email/jaimepavonp@gmail.com