@host = http://localhost:3000

### ----------------------Peticiones CATEGORIAS------------
### GET todas las categorias
GET {{host}}/api/categorias

### GET una categoria por id
GET {{host}}/api/categorias/5